/*
 * Problem: 1304. Find N Unique Integers Sum up to Zero
 * Difficulty: Easy
 * Language: java
 * Submitted: 6/1/2025, 6:07:05 PM
 * LeetCode URL: https://leetcode.com/problems/find-n-unique-integers-sum-up-to-zero/
 * 
 * Auto-generated by LeetCode GitHub Extension
  */

class Solution {
    public int[] sumZero(int n) {

        int[] result = new int[n] ;
        int num = 1; 

        for (int i = 0 ; i < n/2 ; i++) {
            result[i] = -num ;
            result[n - 1 - i] = num ;
            num++;
