#
 * Problem: 66. Plus One
 * Difficulty: Easy
 * Language: python
 * Submitted: 6/1/2025, 6:55:17 PM
 * LeetCode URL: https://leetcode.com/problems/plus-one/
 * 
 * Auto-generated by LeetCode GitHub Extension
 

class Solution(object):
    def plusOne(self, digits):
        total = 0
        for digit in digits:
            total = digit + total * 10

        total += 1
        length = len(str(abs(total)))
        solution = [0] * length
        i = length - 1
