#
 * Problem: 989. Add to Array-Form of Integer
 * Difficulty: Easy
 * Language: python
 * Submitted: 6/1/2025, 9:40:57 PM
 * LeetCode URL: https://leetcode.com/problems/add-to-array-form-of-integer/
 * 
 * Auto-generated by LeetCode GitHub Extension
 

class Solution(object):
    def addToArrayForm(self, num, k):
        """
        :type num: List[int]
        :type k: int
        :rtype: List[int]
        """
        # Transform Array To number
        sum_val = 0
        for digit in num:
